apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mychart-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: {{ printf "front.%s.sslip.io" .Values.hostIP }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mychart-service
            port:
              number: 80
