apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ea-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: {{ printf "ea.%s.sslip.io" .Values.hostIP }}
    http:
      paths:
      - path: /api(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: back-service
            port:
              number: 80
        annotations:
          nginx.ingress.kubernetes.io/rewrite-target: /$2
      - path: /
        pathType: Prefix
        backend:
          service:
            name: front-service
            port:
              number: 80
        annotations:
          nginx.ingress.kubernetes.io/rewrite-target: /$0
