pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                nodejs(nodeJSInstallationName: 'latest') {
                    dir('evidencijaaparata.client') {
                        sh 'npm i'
                        sh 'ng build'
                    }
                }
            }
        }
        stage('Release') {
            steps {
                dir('evidencijaaparata.client') {
                    sh 'ls -lhtra'
                    def myImage = docker.build("ajovano/ajovano")
                    // myImage.push()
                }
            }
        }

    }
    /*
    post {
        always {
            cleanWs()
        }
    }
    */
}