pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                nodejs(nodeJSInstallationName: 'latest') {
                    sh '''
                        ls -lhtra
                        cd ./evidencijaaparata.client
                        ls -lhtra
                        npm i
                        ng build
                    '''
                }
            }
        }
        stage('Deploy') {
            steps {
                sh 'pwd'
                sh 'ls -lhtra'
                // def myImage = docker.build("ajovano/ajovano")
                // myImage.push()
            }
        }
    }
    post {
        always {
            cleanWs()
        }
    }
}