// <auto-generated />
using EvidencijaAparata.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EvidencijaAparata.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240904223337_V1")]
    partial class V1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EvidencijaAparata.Server.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Naziv = "City 1"
                        },
                        new
                        {
                            Id = 2,
                            Naziv = "City 2"
                        },
                        new
                        {
                            Id = 3,
                            Naziv = "City 3"
                        },
                        new
                        {
                            Id = 4,
                            Naziv = "City 4"
                        },
                        new
                        {
                            Id = 5,
                            Naziv = "City 5"
                        });
                });

            modelBuilder.Entity("EvidencijaAparata.Server.Models.GMLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IP")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MestoId")
                        .HasColumnType("integer");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("rul_base_id")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MestoId");

                    b.ToTable("GMLocations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Adresa = "Adresa 1",
                            IP = "192.168.0.1",
                            MestoId = 1,
                            Naziv = "Lokacija 1",
                            rul_base_id = 1
                        },
                        new
                        {
                            Id = 2,
                            Adresa = "Adresa 2",
                            IP = "192.168.0.2",
                            MestoId = 2,
                            Naziv = "Lokacija 2",
                            rul_base_id = 2
                        },
                        new
                        {
                            Id = 3,
                            Adresa = "Adresa 3",
                            IP = "192.168.0.3",
                            MestoId = 3,
                            Naziv = "Lokacija 3",
                            rul_base_id = 3
                        },
                        new
                        {
                            Id = 4,
                            Adresa = "Adresa 4",
                            IP = "192.168.0.4",
                            MestoId = 4,
                            Naziv = "Lokacija 4",
                            rul_base_id = 4
                        },
                        new
                        {
                            Id = 5,
                            Adresa = "Adresa 5",
                            IP = "192.168.0.5",
                            MestoId = 5,
                            Naziv = "Lokacija 5",
                            rul_base_id = 5
                        });
                });

            modelBuilder.Entity("EvidencijaAparata.Server.Models.GMLocation", b =>
                {
                    b.HasOne("EvidencijaAparata.Server.Models.City", "Mesto")
                        .WithMany()
                        .HasForeignKey("MestoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mesto");
                });
#pragma warning restore 612, 618
        }
    }
}
